---
version: '3.8'
services:
  myjenkins:
    image: jenkins/jenkins
    ports: 
      - 50:8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.01"
          memory: "150M"

  qaserver:
    image: tomee
    ports:
      - 60:8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "300M"

  prodserver:
    image: tomee
    ports:
      - 70:8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.01"
          memory: "300M"

